config/routes.rb
Recruiter::Application.routes.draw do
  resources :profiles

  resources :properties

  devise_for :subjects

  resources :events

  resources :recruitments

  get "calendar/index"
  get "calendar", :to => "calendar#index"

  authenticate :subject do
    root :to => "profiles#index"
  end

  root :to => "devise/sessions#new"
  resources :experiments

end

app/models/recruitment.rb
class Recruitment < ActiveRecord::Base
  field :experiment_trial_id
  field :allow_repeat_subjects, :type => :boolean, :default => false
  field :minimum_participants,  :type => :integer
  field :maximum_participants,  :type => :integer
  field :number_to_email,       :type => :integer

  belongs_to :experiment_trial
  has_many :experiment_participants
  has_many :experiment_invitations
  has_many :profiles, :through => :experiment_participants
  has_many :invitees, :through => :experiment_invitations, :source => :profile

  validates_presence_of :maximum_participants

  after_create :populate_invitees

  def populate_invitees
    profiles = Profile.scoped
    profiles = profiles.not_in_experiment(experiment_trial) unless allow_repeat_subjects
    #profiles = filter_restrictions(profiles) if restrictions  # TODO
    profiles.sample(target_emails).each {|p| ExperimentInvitation.create(:profile_id => p.id, :recruitment_id => id)}
  end
end
Recruitment.auto_upgrade!

app/controllers/recruitments_controller.rb
class RecruitmentsController < ApplicationController
  # GET /recruitments
  # GET /recruitments.json
  def index
    @recruitments = Recruitment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recruitments }
    end
  end

  # GET /recruitments/1
  # GET /recruitments/1.json
  def show
    @recruitment = Recruitment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recruitment }
    end
  end

  # GET /recruitments/new
  # GET /recruitments/new.json
  def new
    @recruitment = Recruitment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recruitment }
    end
  end

  # GET /recruitments/1/edit
  def edit
    @recruitment = Recruitment.find(params[:id])
  end

  # POST /recruitments
  # POST /recruitments.json
  def create
    @recruitment = Recruitment.new(params[:recruitment])

    respond_to do |format|
      if @recruitment.save
        format.html { redirect_to @recruitment, notice: 'Recruitment was successfully created.' }
        format.json { render json: @recruitment, status: :created, location: @recruitment }
      else
        format.html { render action: "new" }
        format.json { render json: @recruitment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recruitments/1
  # PUT /recruitments/1.json
  def update
    @recruitment = Recruitment.find(params[:id])

    respond_to do |format|
      if @recruitment.update_attributes(params[:recruitment])
        format.html { redirect_to @recruitment, notice: 'Recruitment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @recruitment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recruitments/1
  # DELETE /recruitments/1.json
  def destroy
    @recruitment = Recruitment.find(params[:id])
    @recruitment.destroy

    respond_to do |format|
      format.html { redirect_to recruitments_url }
      format.json { head :no_content }
    end
  end
end

app/views/recruitments/_form.html.erb
<%= simple_form_for(@recruitment) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="control-group">
    <div class="controls">
      <%= f.input :allow_repeat_subjects %>
    </div>
    <div class="controls">
      <%= f.input :minimum_participants %>
    </div>
    <div class="controls">
      <%= f.input :maximum_participants %>
    </div>
    <div class="controls">
      <%= f.input :number_to_email %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/recruitments/edit.html.erb
<h1>Editing recruitment</h1>

<%= render 'form' %>

<%= link_to 'Show', @recruitment %> |
<%= link_to 'Back', recruitments_path %>

app/views/recruitments/index.html.erb
<h1>Listing recruitments</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @recruitments.each do |recruitment| %>
  <tr>
    <td><%= link_to 'Show', recruitment %></td>
    <td><%= link_to 'Edit', edit_recruitment_path(recruitment) %></td>
    <td><%= link_to 'Destroy', recruitment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Recruitment', new_recruitment_path %>

app/views/recruitments/new.html.erb
<h1>New recruitment</h1>

<%= render 'form' %>

<%= link_to 'Back', recruitments_path %>

app/views/recruitments/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_recruitment_path(@recruitment) %> |
<%= link_to 'Back', recruitments_path %>