config/routes.rb
Recruiter::Application.routes.draw do
  resources :profiles

  resources :properties

  devise_for :subjects

  resources :events

  resources :recruitments

  get "calendar/index"
  get "calendar", :to => "calendar#index"

  authenticate :subject do
    root :to => "profiles#index"
  end

  root :to => "devise/sessions#new"
  resources :experiments

end

app/models/property.rb
class Property < ActiveRecord::Base
  attr_accessible :choices_attributes, :name, :text, :response, :multiple_choice, :mutually_exclusive
  field :name
  field :text
  field :response
  field :multiple_choice, :type => :boolean
  has_many :choices
  accepts_nested_attributes_for :choices
  field :mutually_exclusive, :type => :boolean
end
Property.auto_upgrade!

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @properties }
    end
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
    @property = Property.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @property }
    end
  end

  # GET /properties/new
  # GET /properties/new.json
  def new
    @property = Property.new
    @property.choices.build
    @property.choices.first.save

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @property }
    end
  end

  # GET /properties/1/edit
  def edit
    @property = Property.find(params[:id])
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(params[:property])

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render json: @property, status: :created, location: @property }
      else
        format.html { render action: "new" }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /properties/1
  # PUT /properties/1.json
  def update
    @property = Property.find(params[:id])

    respond_to do |format|
      if @property.update_attributes(params[:property])
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property = Property.find(params[:id])
    @property.destroy

    respond_to do |format|
      format.html { redirect_to properties_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.erb
<%= simple_nested_form_for @property, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Property</legend>
    <%= f.input :name %>
    <%= f.input :text %>
    <%= f.input :multiple_choice %>
    <%= f.input :mutually_exclusive%>
    <%= f.simple_fields_for :choices do |c| %>
      <%= c.input :text %>
      <%= c.link_to_remove "Remove this choice" %>
    <% end %>
    <%= f.link_to_add "Add a choice", :choices %>


    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', properties_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/properties/edit.html.erb
<%= render :partial => 'form' %>

app/views/properties/index.html.erb
<h1>Propertys</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Created at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.id %></td>
        <td><%= link_to property.name, property_path(property) %></td>
        <td>
          <%= link_to 'Edit', edit_property_path(property), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', property_path(property), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_property_path, :class => 'btn btn-primary' %>

app/views/properties/new.html.erb
<%= render :partial => 'form' %>

app/views/properties/show.html.erb
<h1>Property</h1>

<p>
  <b>Name</b><br>
  <%= @property.name %>
</p>

<p>
  <b>Text</b><br>
  <%= @property.text %>
</p>

<p>
  <b>Multiple choice</b><br>
  <%= @property.multiple_choice %>
</p>

<div class="form-actions">
  <%= link_to 'Back', properties_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_property_path(@property), :class => 'btn' %>
  <%= link_to 'Delete', property_path(@property), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>