config/routes.rb
Recruiter::Application.routes.draw do
  resources :profiles

  resources :properties

  devise_for :subjects

  resources :events

  resources :recruitments

  get "calendar/index"
  get "calendar", :to => "calendar#index"

  authenticate :subject do
    root :to => "profiles#index"
  end

  root :to => "devise/sessions#new"
  resources :experiments

end

app/models/experiment.rb
class Experiment < ActiveRecord::Base
  field :name
  field :title
  field :description
  field :category_id,         :type => :integer
  field :created_at,          :type => :datetime

  has_many :experiment_trials

  belongs_to :category


end
Experiment.auto_upgrade!

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  # GET /experiments
  # GET /experiments.json
  def index
    @experiments = Experiment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @experiments }
    end
  end

  # GET /experiments/1
  # GET /experiments/1.json
  def show
    @experiment = Experiment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @experiment }
    end
  end

  # GET /experiments/new
  # GET /experiments/new.json
  def new
    @experiment = Experiment.new
    @experiment.events.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @experiment }
    end
  end

  # GET /experiments/1/edit
  def edit
    @experiment = Experiment.find(params[:id])
  end

  # POST /experiments
  # POST /experiments.json
  def create
    @experiment = Experiment.new(params[:experiment])

    respond_to do |format|
      if @experiment.save
        format.html { redirect_to @experiment, notice: 'Experiment was successfully created.' }
        format.json { render json: @experiment, status: :created, location: @experiment }
      else
        format.html { render action: "new" }
        format.json { render json: @experiment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /experiments/1
  # PUT /experiments/1.json
  def update
    @experiment = Experiment.find(params[:id])

    respond_to do |format|
      if @experiment.update_attributes(params[:experiment])
        format.html { redirect_to @experiment, notice: 'Experiment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @experiment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experiments/1
  # DELETE /experiments/1.json
  def destroy
    @experiment = Experiment.find(params[:id])
    @experiment.destroy

    respond_to do |format|
      format.html { redirect_to experiments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/views/experiments/_form.html.erb
<%= form_for @experiment, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Experiment</legend>

    <div class="control-group">
      <%= f.label :title, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :title, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :description, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :description, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :target_participants, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :target_participants, :class => 'text_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', experiments_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/experiments/edit.html.erb
<%= render :partial => 'form' %>

app/views/experiments/index.html.erb
<h1>Experiments</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Created at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @experiments.each do |experiment| %>
      <tr>
        <td><%= experiment.id %></td>
        <td><%= link_to experiment.title, experiment_path(experiment) %></td>
        <td><%= experiment.created_at %></td>
        <td>
          <%= link_to 'Edit', edit_experiment_path(experiment), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', experiment_path(experiment), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_experiment_path, :class => 'btn btn-primary' %>

app/views/experiments/new.html.erb
<%= render :partial => 'form' %>

app/views/experiments/show.html.erb
<h1>Experiment</h1>

<p>
  <b>Title</b><br>
  <%= @experiment.title %>
</p>

<p>
  <b>Location</b><br>
  <%= @experiment.description %>
</p>

<div class="form-actions">
  <%= link_to 'Back', experiments_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_experiment_path(@experiment), :class => 'btn' %>
  <%= link_to 'Delete', experiment_path(@experiment), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>